const express = require("express");
const authRoutes = require("./auth.routes");
const propertyRoutes = require("./property.routes");
const userRoutes = require("./user.routes");
const bookingRoutes = require("./booking.routes");
const unitRoutes = require("./unit.routes");
const unitTypeRoutes = require("./unitType.routes");
const leaseRoutes = require("./lease.routes");
const paymentRoutes = require("./payment.routes");
const invoiceRoutes = require("./invoice.routes");
const maintenanceRoutes = require("./maintenance.routes");
const inspectionRoutes = require("./inspection.routes");
const notificationRoutes = require("./notification.routes");
const documentRoutes = require("./document.routes");
const auditlogRoutes = require("./auditlog.routes");
const searchRoutes = require("./search.routes");
const communicationRoutes = require("./communication.routes");
const dashboardRoutes = require("./dashboard.routes");
const incidentRoutes = require("./incident.routes");

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/properties", propertyRoutes);
router.use("/incidents", incidentRoutes);
router.use("/users", userRoutes);
router.use("/bookings", bookingRoutes);
router.use("/units", unitRoutes);
router.use("/unit-types", unitTypeRoutes);
router.use("/leases", leaseRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/finance", paymentRoutes);
router.use("/maintenance", maintenanceRoutes);
router.use("/inspections", inspectionRoutes);
router.use("/notifications", notificationRoutes);
router.use("/documents", documentRoutes);
router.use("/auditlogs", auditlogRoutes);
router.use("/search", searchRoutes);
router.use("/communication", communicationRoutes);

module.exports = router;